### ISSUE TITLE
Token sync problem

### ISSUE THREAD

**Issue by ramagirinagarjuna** [mattrubin/Authenticator#106]
Hi,

For few sites like slack.com the token generated is working perfectly. But, for some other sites, the token generated is working only after some time (i.e I need to wait for around 10secs). Request you to look into the issue.

Thanks,
Nagarjuna

**Comment by ramagirinagarjuna** [comment]
I found the reason behind this issue. Because logged in to the website from a system which has a time difference of around 10secs to the system in which the application is running. I think for google, slack, dropbox this was automatically corrected at the backend but for some other sites this is not happening.

**Comment by mattrubin** [comment]
Unfortunately, clock drift can be a problem when validating time-based OTPs. The TOTP RFC [recommends](https://tools.ietf.org/html/rfc6238#section-6) that the "validator" (the website accepting the OTP) should accept a small range of passwords to compensate for clock drift, but it seems like only some of the sites you were logging into actually do this.
