### ISSUE TITLE
Build failed in Xcode 7.3.1

### ISSUE THREAD

**Issue by cropd** [mattrubin/Authenticator#112]
Hi,

I followed the "Getting Started" instructions but I'm getting errors when I build the Authenticator scheme in `Authenticator.xcworkspace`:

> <unknown>:0: error: underlying Objective-C module 'OneTimePassword' not found
> /Users/user/pathtoiosdir/Authenticator/Carthage/Checkouts/OneTimePassword/OneTimePassword/Token+URL.swift:27:8: error: no such module 'Base32'
> import Base32

What am I doing wrong?
(Xcode 7.3.1)

**Comment by mattrubin** [comment]
It looks like following my original instructions for checking our submodules would result in the submodules' submodules not being checked out properly. I fixed the "Getting Started" instructions in pull request #114.
