### ISSUE TITLE
Add a search filter

### ISSUE THREAD

**Issue by chiedo** [mattrubin/Authenticator#113]
Hey Matt!
Just chimed you on Twitter.

What are the chances you could add a search filter. It would make it way easier to find what you were looking for if you had 100 different accounts set up, etc.

**Comment by mattrubin** [comment]
Closed by #134.

**Comment by chiedo** [comment]
This is awesome! :) Right on my birthday took did you know? ;) 

When will this hit the App Store?

**Comment by chiedo** [comment]
too*
