### ISSUE TITLE
Contribution Difficulty

### ISSUE THREAD

**Issue by rastreus** [mattrubin/Authenticator#13]
@mattrubin,

I really enjoy the clean simplicity of this app and would like to contribute to some of the new features that have been requested (TouchID/PIN, Notification Center Widget, possibly a WatchKit addition), but I'm not sure where to start.

Cloning and building the master branch resulted in build failures due to the dependencies. It's difficult to start contributing since dependencies are managed by both Carthage and Cocoapods. I see that you're transitioning to Carthage; possibly move SVProgressHUD so a single carthage bootstrap gets contributors up and running.

Also, a CONTRIBUTING.md file would be helpful like Github's guide states:
[Contributing to Open Source](https://guides.github.com/activities/contributing-to-open-source/)

**Comment by mattrubin** [comment]
Thanks for the feedback! The transition from CocoaPods to Carthage is complete, the README now has ["Getting Started" instructions][getting-started], and I've added some basic [guidelines for contributing][contributing].

If you have any more suggestions on how I can make it easier to contribute, please let me know.

[getting-started]: https://github.com/mattrubin/Authenticator/blob/master/README.md#getting-started
[contributing]: https://github.com/mattrubin/Authenticator/blob/master/CONTRIBUTING.md
