### ISSUE TITLE
Progress ring does not update when scrolling

### ISSUE THREAD

**Issue by beaucollins** [mattrubin/Authenticator#136]
Steps to reproduce:

First make sure you have at least one token and the ring is displaying.

1. Drag to scroll view while watching the progress ring
2. Note the ring doesn't update
3. Lift finger to release scrolling
4. See ring jump to correct position

What I expect:

The ring should continue to animate while the tokens are being scrolled.

**Comment by beaucollins** [comment]
The fix to allow animation updates during scrolling is to schedule the`CADisplayLink` on `NSRunLoopCommonModes`.

However, after doing this the `UITableView` scrolling over-animates its scrolling.

My assumption is that it has to do with [updating the table view with `.beginUpdates` and `.endUpdates`](https://github.com/mattrubin/Authenticator/blob/28d32f129f34ee82912d5d6290cc4249a06384e6/Authenticator/Source/TokenListViewController.swift#L196-L215) every time the state model changes. If you comment out [`updateTableViewWithChanges(changes)`](https://github.com/mattrubin/Authenticator/blob/28d32f129f34ee82912d5d6290cc4249a06384e6/Authenticator/Source/TokenListViewController.swift#L186) the scrolling problem goes away.

**Comment by mattrubin** [comment]
It looks like this bug also affected time-based password updates, because `tick` wouldn't fire at all while the user dragged the scroll view. Unless a cell containing a time-based token scrolled offscreen and back on, the TOTP in the cell would not update.
