### ISSUE TITLE
exception on build test on ios 8.4.1

### ISSUE THREAD

**Issue by secmask** [mattrubin/Authenticator#155]
I try to build and test this app using ios 8.4.1 (OSX capital, Xcode 8.1), and I get this error when the app run on device:

```
/Users/secmask/projects/xcode-projects/Authenticator/Authenticator/Source/TokenListViewController.swift: 28: 7: fatal error: use of unimplemented initializer 'init(nibName:bundle:)' for class 'Authenticator.TokenListViewController'

warning: could not load any Objective-C class information from the dyld shared cache. This will significantly reduce the quality of type information available.
```

Just wonder how to fix it. thanks.

**Comment by beaucollins** [comment]
The fix is to add the missing initializer.

Here's an example: beaucollins/Authenticator#3

I'm not sure why it fails on iOS 8 but not on iOS 9+

**Comment by beaucollins** [comment]
Actually, it looks like an even better alternative is to change the `super.init` call to use `init(nibName:bundle)` instead of `init(style:)`.

https://gist.github.com/beaucollins/c544983eb4a11c0f06dae41abf5ae06a

**Comment by secmask** [comment]
:+1:

**Comment by mattrubin** [comment]
Thanks for finding a simple solution, @beaucollins!
