### ISSUE TITLE
Keychain storage

### ISSUE THREAD

**Issue by rierdev** [mattrubin/authenticator#178]
When i delete the authenticator app on my iPhone and reinstall the app, all of the entries get restored! This is great because the Google Authenticator used to loose all of my entries and they are not easy to re-create.

However, when I install the app on my iPad, it doesn't create the same entries as on the iPhone. Is the authenticator data specific to the device? I would have expected them to be restored to the iPad. In an emergency, if I lost the actual device and replaced with a new device, would it properly restore the entries from iCloud Keychain as long as I am logging in with the same iCloud ID?

**Comment by beaucollins** [comment]
The authenticator codes are stored in your user's keychain on the device. Currently the keychain items for the app are not configured to sync.

The only way to back up your tokens is to use an encrypted backup via iTunes.

See #6 for the discussion on enabling syncing.

**Comment by mattrubin** [comment]
I'm also working on #145 to make this limitation more clear to new users.
