### ISSUE TITLE
 I lost all the codes

### ISSUE THREAD

**Issue by pdgmicro1895** [mattrubin/authenticator#179]
Merci d’avoir choisi Apple.
Cher Monsieur Christian Blouin,

Merci d’avoir contacté l’iTunes Store. Mon prénom est Anna et j'aurai le plaisir de prendre en charge votre requête.

D’après votre e-mail, je comprends que vous avez perdu tous vos codes avec “authenticator”. Vous voulez savoir comment faire pour récupérer vos codes.

Je comprends tout à fait l’importance de pouvoir y avoir accès afin de profiter pleinement de votre application.

Rassurez-vous que je vais faire de mon mieux pour trouver la meilleure solution possible qui convient à votre cas.

En effet, pour obtenir de l’aide à ce sujet, veuillez contacter le développeur de l’application. Les développeurs sont la meilleure ressource dans ces situations car ils peuvent examiner le problème avec leurs outils. Voici un lien vers son site Web :

http://mattrubin.me/authenticator/

Sachez que c’est le développeur qui pourrait vous aider à résoudre votre souci de manière definitive.

Pourtant, si votre problème persiste, veuillez nous le fare savoir.

Nous de notre part, nous ne pouvons qu’examiner la possibilité d’un éventuel remboursement. En ce cas, si vous avez fait des achats depuis cette application que vous n’avez pas reçus ou auxquels vous n’avez plus accès, veuillez me communiquer leur numéro de commande. Pour retrouver le numéro de commande d’un achat, procédez comme indiqué dans l’article suivant :

http://support.apple.com/fr-fr/HT204088

Veuillez également m’indiquer l’identifiant Apple lié au compte depuis lequel vous avez acheté l’application en question.

Je vous remercie de votre coopération. La résolution de votre affaire est importante à mes yeux et j’attends votre réponse. 

Au plaisir de vous lire, je vous souhaite une excellente journée.

Cordialement,

Anna Arkolaki
Le service clientèle de l’iTunes Store
http://www.apple.com/support/itunes/ww
Apple Inc., de la part de Apple Distribution International
NB: Notre département fonctionne du Lundi au Dimanche de 8:00 à 20:00.

On Feb 10, 2017, at 23:00 christian blouin <pdgmicro@icloud.com> wrote:

> Produit  iTunes Store
>  
> Catégorie d’assistance  Gestion des comptes
> Rubrique d’assistance  
>  
> Informations supplémentaires
>  
> Choisissez l’iTunes Store ou l’App Store de votre pays : Canada
>  
>  
> Commentaires supplémentaires
> Itunes,
> Dans section sauvegarde
> avec cet ordinateur j'ai fait sauvegarde maintenant.
> avec mon iphone 6+ 
> je ne voie plu mes codes avec authenticator, j'ai tout perdu les code !!! J'ai fait restaure maintenant aucun résulta positif pas de code dans mon application,comment faire pour retrouvez .
Merci

Additional Comments
> Itunes,
> In saving section
> With this computer I made backup now.
> With my iphone 6+
> I do not see more my codes with authenticator, I lost all the codes !!! I have now restored no positive result no code in my application, how to find it.
Thank you

**Comment by mattrubin** [comment]
For security reasons, the tokens in Authenticator – like other saved passwords on iOS – are only included in a backup [if that backup is encrypted](https://support.apple.com/en-us/HT205220). If you use an iCloud backup or an iTunes backup without encryption, you might lose your tokens. I'm sorry that this limitation wasn't made more clear when you set up two-factor authentication.

When you set up two-factor authentication for a website, you should have been given recovery codes or some other backup method of accessing your account. Hopefully, you can use this to restore access and set up a new two-factor token.

---

Je vais essayer en français:

Pour raisons de la sécurité, les codes dans Authenticator – comme des autres mots de passe enregistrés en iOS – sont inclus dans une sauvegarde seulement [si cette sauvegarde est chiffrée](https://support.apple.com/fr-ca/HT205220). Si vous utilisez une sauvegarde iCloud ou une sauvegarde iTunes sans chiffrement, vous pourriez perdre vos codes. Je suis désolé que cette limitation n'a pas été rendu plus clair lorsque vous avez configuré l'authentification à deux facteurs.

Quand vous avez configuré l'authentification à deux facteurs pour un site, le site aurait dû vous donner quelques "recovery codes" ou une autre méthode de récupération de l'accès à votre compte. J'espère que vous pouvez l'utiliser pour restaurer l'accès à votre compte et reconfigurer l'authentification à deux facteurs.
