### ISSUE TITLE
Accidently removed account from Authenticaor now account/app cannot be accessed

### ISSUE THREAD

**Issue by 0zzie1** [mattrubin/authenticator#193]
Hi,
I am using Authenticator and i added access for an account/app on the Authenticator app and my son deleted it from the Authenticator app. Now access to that app is blocked, because it is not showing up on Authenticator. 

Is there anyway to gain access to the app/account again? It was a Roku channel for which i added a code managed by Authenticator.

**Comment by beaucollins** [comment]
You will have to contact Roku and go through whatever recovery process they may have to disable two-factor authentication.

If you have an encrypted backup of your device in iTunes from before it was deleted from the app you may be able to recover it by restoring your device using the backup.
