### ISSUE TITLE
Ask for confirmation before deleting entries

### ISSUE THREAD

**Issue by scribblemaniac** [mattrubin/authenticator#198]
I was deleting my passwords (intentionally) today, and it occurred to me that there should probably be some sort of warning before you can delete a password. Given that if you don't have an encrypted backup then you've probably lost access to that account forever, having a confirmation dialog pop up when trying to delete a password will reduce the risk of someone accidentally deleting it or deleting it without realizing the potential consequences.

**Comment by beaucollins** [comment]
I think it might be a good idea to remove the delete by swiping feature as well.

Deleting a token probably is not done often and doesn't need to be so easily available to users. Educating users on the ramifications of deleting a token would be worthwhile as well.

**Comment by mattrubin** [comment]
Swipe-to-delete was removed by PR #251, and will be released with Authenticator 2.0.3.
An additional delete confirmation alert was added by PR #217, and will be released with Authenticator 2.1.
Issue #275 has been opened to track the idea of adding an "undo" user flow to restore a deleted token.
