### ISSUE TITLE
Getting started manual??

### ISSUE THREAD

**Issue by JulieLedwon** [mattrubin/authenticator#200]
Am I the only one who has no idea where to start?? I install the app, get a screen that says No Tokens, Tap + to add a new token. Ok, so no option except to hit the plus sign. I hit it and I have to scan a token...that's where I"m stuck. Where do I get a token? The only reason I'm doing all this is because Coinbase sent me an email saying they recommend I use a better 2 factor authenticator than text messages and recommended "something like google authenticator." Well, that app gets horrible reviews. So here I am - googling for help doesn't produce a getting started manual either. I'm trying...really I am.  Thanks. -Julie

**Comment by mattrubin** [comment]
Hi Julie,

Each token is provided by the online service which uses two-factor authentication – in this case, Coinbase. When you enable two-factor authentication in your Coinbase account settings, the website will present you with a secret token in the form of a QR code or a string of numbers and letters. You can use the token scanner in the app to scan the QR code, saving the token in the app, and then the app can use the token to generate one-time passwords which you will use when logging into the website in the future.

Here is Coinbase's help article on setting up Google Authenticator: https://support.coinbase.com/customer/en/portal/articles/2684672. The same instructions should work for setting up two-factor authentication with this app.

**Comment by JulieLedwon** [comment]
Perfect that worked, thank you!!

**Comment by pixelrogue1** [comment]
Still think this would be worth including in the iOS app itself. It can be a hard intro and a dead app otherwise. Maybe an updated list of apps supported by Authenticator would also be helpful.
