### ISSUE TITLE
i have chance my phone and now i lost my code to verify

### ISSUE THREAD

**Issue by ibrahimpo13** [mattrubin/authenticator#213]
i have chance my phone and now i lost my code to verify  

what must i do to find my code back?

**Comment by mide** [comment]
I hate to say it, but you can't. The whole point (and @mattrubin please correct me if I'm wrong) of these apps is that you can't get the secret back once entered. That means your secret (the piece that makes the six digit numbers) is gone. 

I'd reach out to the service if I were you and start a reset process. 

Edit: Also see #193 and #6 for more help; looks like an encrypted iOS backup may help.
