### ISSUE TITLE
Question: Why three two-digit groups?

### ISSUE THREAD

**Issue by mide** [mattrubin/authenticator#214]
The app used to have two three-digit groups (`123 456`) and a recent(ish) change made it three two-digit groups (`12 34 56`). What was the motivation behind this? 

I'd _love_ the option to put it back to `123 456` as that is easier for me to remember. 

Love the app! Super simple and nothing more than you need. (Plus the fact you can't export is perfect, the way it should be!)

**Comment by beaucollins** [comment]
I agree. I think the only thing to consider is that there can be cases where codes are not six digit numbers. But two groups of three feel preferable to three groups of two.

**Comment by mide** [comment]
That's a fair point, I hadn't thought of those cases. You're right the three two-digit groups would make sense for any evenly sized group. 

I still wonder if there is any way to achieve this...

**Comment by beaucollins** [comment]
Not terribly complicated:

![img_1ee0ac437151-1](https://user-images.githubusercontent.com/19795/32079756-eda6b796-ba60-11e7-90a7-746e207c6f66.jpeg)

**Comment by beaucollins** [comment]
These changes can be seen in #216

**Comment by mide** [comment]
Closing this for #216. PR looks like it accomplishes the goals, so no need to keep this open.
