### ISSUE TITLE
I Accidentally Deleted An "Old" Code. It Was The CURRENT One. Locked Out.

### ISSUE THREAD

**Issue by laurrel** [mattrubin/authenticator#225]
The website I created a super safe password for ended up unable to read the app at first. So I tried again. It was able to read it the second time. So I figured I would delete the unreadable code to prevent future mishaps. Turns out, I somehow accidentally deleted the working code. Now, the website has me completely locked out due to being unable to authorize it with the app. How in the world can I reset it? Is there a way to reset it? Is there a way to remove this authentication from my account (even though I am locked out)? I spoke to the website support and they said I had to contact the app support directly. I am at a complete and utter loss here.

**Comment by beaucollins** [comment]
I'm sorry you've lost access to your account. Did the website provide you with any backup passcodes when you were setting this up?

If you made an encrypted back up of your phone through iTunes it may be recoverable by restoring from that backup.

There's no way this app can enable access to your account if it no longer has the secret code. Tell the website support company you no longer have access to the device that generates your passcodes, they should have their own policies on how to restore access to your account.

Best of luck.

**Comment by laurrel** [comment]
The website was GoDaddy. I had just purchased several domains and am now
unable to access any of them.

GoDaddy doesn’t seem to have the hard reset option. And I can’t use the
authentication process anymore since I accidentally removed the codes (I
thought they just automatically respawned randomly).

**Comment by beaucollins** [comment]
The app generates new codes every 30 seconds, no deleting of codes is necessary for this to work. Since the "Two-Step Generator" was deleted from the app it can no longer generate the codes.

It looks like Godaddy does have a way for you to remove two-step verification when you've lost the ability to generate passcodes:

> ## I can't log in to my account
>
> Download and complete this [Request to Cancel Two-Step Authentication form](https://img4.wsimg.com/support/pdf/mya/twostepcancel2_godaddy.pdf). Please note, this form cannot be signed with an electronic signature.
>
> Along with the necessary identification, email the completed form to twostepcancel@godaddy.com . Use the subject line "Disabling Two-Step Authentication."
>
>  Note: This email needs to come from the email address that's on your account. If you need to update the email address on file, update your email at www.changeupdate.com.
>
> You will receive a reply from us within 72 hours.

https://www.godaddy.com/help/turn-off-two-step-verification-7628

**Comment by laurrel** [comment]
Yeah, my bad. I am pretty clueless when it comes to operating technology.

Thanks for digging up that GoDaddy info! I was literally on the phone with
their support and emailed back and forth with them constantly and *nobody*
came up with a workable solution. I’ll check this out tomorrow and get back
to you.

Cheers

**Comment by beaucollins** [comment]
> 
> Yeah, my bad. I am pretty clueless when it comes to operating technology.

No worries. Technology can be a pain in the butt. At least it appears Godaddy does a good job of verifying account owners when disabling two-factor authentication.

Do you think there’s anything the app could have done better to prevent the confusion you dealt with?
