### ISSUE TITLE
Adapt to iPhone X screen

### ISSUE THREAD

**Issue by popoway** [mattrubin/authenticator#226]
Currently the app doesn’t fully take advantage of the screen.
![35a8983d-105a-4024-aa17-6cd4cc48eb7e](https://user-images.githubusercontent.com/31576265/32417886-e999a27e-c22d-11e7-80cb-03444b0a7cf3.jpeg)

**Comment by beaucollins** [comment]
It looks like releasing a new build using the latest Xcode should be sufficient:

<img width="545" alt="iphone-x" src="https://user-images.githubusercontent.com/19795/32419252-fe4531ae-c22b-11e7-9e51-cd22d524c0b2.png">

**Comment by mattrubin** [comment]
Authenticator [2.0.1](https://github.com/mattrubin/Authenticator/releases/tag/2.0.1) was released today with support for iPhone X.
