### ISSUE TITLE
I didn't save the token. Big oops or fixable?

### ISSUE THREAD

**Issue by Luddite88** [mattrubin/authenticator#237]
Hi Matt, 
I didn't save the token when I used the 6-digit code I was given. And, I didn't write down the code either. Is there a way to find it or a floating token (she says with wry smile) somewhere in the recesses of my phone? I can't access my account without a numeric code. Any guidance you can give this beginner (seriously, my first attempt at this crazy business of authenticating) would be most appreciated. Many thanks.

**Comment by beaucollins** [comment]
Which token are you talking about specifically?

You shouldn’t have to remember/record the six digit codes that the app generates. Every time you log into the account just use the code that is displayed on the app at that time.

Some services give you backup codes that you can use if you can’t access your phone. You’ll want to write/print those somewhere.

**Comment by Luddite88** [comment]
Hi, 

The token on the Authenticator App. This is what happened…I took the photo of my computer screen to start the authentication process, the 6-digit code came up in the app, I typed it into my online account (which was accepted) and then I didn’t save it. By it, I mean the account information to the app (the app states to add a “token”…so I’m using that vernacular). Now, I don’t know how to get it back to access the six digit code. Does that make sense?

Also, I must offer apologies - I’m on a bit of a learning curve. I just figured out after sending the issue report that the code isn’t a one-time static thing. Anyway, I really just need to know if it’s possible to retrieve the account info/6-digit access code from the app. Right now, I open the app and there’s no record of any access code having been created. 

Thanks very much for your help and patience!
Erin

**Comment by beaucollins** [comment]
No worries Erin. Let's see what we can figure out.

When you open the app is this what you see?

![img_0824262ec449-1 2](https://user-images.githubusercontent.com/19795/32960429-b12e5f1a-cb79-11e7-8c87-4d35a23e779b.jpeg)

What you describe indicates that you successfully added the password generator to the app and it should have been saved. At any point did you hit a red "Delete" button? That should be the only way to delete the password generator from the app once you've gotten to the point where it displays a 6 digit code.

If the app no longer has the password generator that you used to get the 6 digit code there is no way to recover it. You will have to remove two factor authentication on your account and start the setup process over.

If you no longer have access to your account you will have to go through the website's account recovery steps.

**Comment by Luddite88** [comment]
Yep…so blank. I fear the info fell into some dark vortex. Tell me it’s not so!

**Comment by beaucollins** [comment]
Yeah, unfortunately it seems to have fallen into this vortex you speak of. 

The curious thing is that once you've reached the point in the app that it shows you a 6 digit code it _should_ at that point be saved and remain in the app until you delete it.

At this point you need to disable/re-enable two factor on your account.

**Comment by Luddite88** [comment]
Hmmm, it didn’t. This is vexing. But, I very much appreciate your help with my little conundrum. 

Now, if you could deal with customer service for me, that would be fantastic. Ha. 

Thanks!
Erin

**Comment by Luddite88** [comment]
Hi, 

I used this e-mail once before when I was having some technical issues. You were so helpful, I thought I try again in the hopes you might indulge my quest for understanding how this thing works. 

If I save the Authenticator App with all of my “transactions” (for lack of a better word) to my computer and/or iCloud (with the encryption on), I can still always recover it even if I lose my iphone. Is that right? Or, is there something else I need to do to ensure I can still access my codes in the event of a lost phone? 

I’m just making sure - crossing my t’s, if you will - before I go for round 2. 

Many thanks and happy new year!
Erin

**Comment by beaucollins** [comment]
@Luddite88 you're mostly correct but I need to make one thing clear.

The "Encrypt iPhone backup" option in iTunes only applies to backups stored on the computer, **not in iCloud**. Your Authenticator's secret codes are never stored in iCloud so restoring from an iCloud backup will _never_ restore your secret codes.

If you want to be absolutely certain that you have backed up your Authenticator codes:

1. Open iTunes and go your phone's "Summary"
2. In the "Backups" section make sure the "Encrypt iPhone backup" checkbox is checked. If not, then check it and enter a password to use for encryption.
3. Under the "Manually Back Up and Restore" section of "Backus" click "Back Up Now"

Once this is completed you will have backed up Authenticator's secrets as they are at that moment in time.

If you plug in a different phone and click "Restore Backup ..." and choose the encrypted backup you just made, the device will have the Authenticator app _and_ the secret codes restored.

**Comment by Luddite88** [comment]
Brilliant! You are a god among men...thanks for taking the time to explain in such detail.. 
Erin
