### ISSUE TITLE
authenticator for outlook/microsoft

### ISSUE THREAD

**Issue by knockout-kevin** [mattrubin/authenticator#243]
I have been using authenticator app for my gmail and hotmail accounts for few years but after getting a new phone, I can not find the QR code or the secret key to scan token for Microsoft from the new phone. Please help.

**Comment by beaucollins** [comment]
To set up a new two-factor token on your new phone you need to go through the set up process again on the website that hosts your account.

I don't use outlook so I'm not familiar with their exact process. Usually it's just a matter of disabling two-factor on the account then going through the steps to set it up again (but this time use your new phone to scan the code).

The secret tokens should be treated as though they are stuck inside the specific device they are installed on. So to set up a new device, you'll need to get a brand new secret token.

**Comment by knockout-kevin** [comment]
Thanks Beau. I had turned off and restarted the process for Microsoft but did not give me options for QR code to use this authenticator app. I was forced to use one of theirs for 2-factor authentication, which I had to do reluctantly. I was more optimistic earlier since I had been using it for few years now but now I will not be able to use this app anymore 😔

Once again, thanks for your help.

Kunal Patel

On Dec 5, 2017, at 7:47 PM, Robert “Beau” Collins <notifications@github.com<mailto:notifications@github.com>> wrote:


To set up a new two-factor token on your new phone you need to go through the set up process again on the website that hosts your account.

I don't use outlook so I'm not familiar with their exact process. Usually it's just a matter of disabling two-factor on the account then going through the steps to set it up again (but this time use your new phone to scan the code).

The secret tokens should be treated as though they are stuck inside the specific device they are installed on. So to set up a new device, you'll need to get a brand new secret token.

**Comment by beaucollins** [comment]
I took a quick look at the Outlook settings. During the "Identity verification apps" process on the "Additional security options" page you can choose the "Other" option which will provide you with the QR code:

![screen shot 2017-12-06 at 9 03 55 am](https://user-images.githubusercontent.com/19795/33674439-67a2cf58-da64-11e7-9fca-daabd4922f39.png)

If you choose "iPhone, iPad or iPod touch" (and probably any of the other options) it will make you use their app.
