### ISSUE TITLE
Feature Request: (Optional) Device Passcode / Touch ID / Face ID Support

### ISSUE THREAD

**Issue by beeeswax** [mattrubin/authenticator#278]
First, thank you again for this delightful app I use every day! 💯

I was just using my favorite MFA app (Authenticator), and the thought crossed my mind that optional Device Passcode / Face ID / Touch ID support in Authenticator would be awesome.

I think Signal does this well, from a user perspective. (No idea how well they do it from a developer perspective.)

Thank you!

**Comment by BrunoMiguens** [comment]
Is it possible to create a PR in order to create this feature? or needs discussion/approval?

**Comment by mattrubin** [comment]
An excellent feature request, @beeeswax! I'm going to close this issue to move discussion over to [the original issue filed for this feature](https://github.com/mattrubin/Authenticator/issues/1).

(@BrunoMiguens, I've replied to your comment in the other thread.)
