### ISSUE TITLE
Encrypted Restore to Ipad does not work.

### ISSUE THREAD

**Issue by MrMonotone** [mattrubin/authenticator#279]
Since the app does not support Ipads, restoring the encrypted backup does not seem to work.

**Comment by mattrubin** [comment]
I'm sorry for the long-overdue reply!

This project has been unmaintained for several years, and as I work to catch up on all of the open issues and feedback, I'm closing all issues older than a year. If, after all this time, you still have a question or are in need of help with the app, please feel free to re-open this issue.
