### ISSUE TITLE
iPhone update from iPhone6 to iPhone X

### ISSUE THREAD

**Issue by idealink0** [mattrubin/authenticator#295]
Is there a risk to loose Key to upgrade iPhone?   What is the proper step to upgrade to a new iPhone?

**Comment by mattrubin** [comment]
To move your Authenticator tokens to a new phone, you will need to make an *encrypted* backup of your old phone using iTunes. You will then need to restore the encrypted backup onto the new phone. If possible, I reccomend restoring the new phone and confirming you have your tokens before erasing your old phone.

**If you do not set up your new phone from an encrypted iTunes backup of your old phone, your tokens will be lost.**

You can learn more about how to make an encrypted iTunes backup from this Apple support article: https://support.apple.com/en-us/HT205220

**Comment by idealink0** [comment]
Thank you for the timely reply.

**Comment by digemfn** [comment]
I lost my backup codes and need help getting them back.

**Comment by fiddlegulch** [comment]
I restored my phone from an encrypted backup as was instructed and my keys were all lost anyway.
