### ISSUE TITLE
Lost security code or backup codes 

### ISSUE THREAD

**Issue by digemfn** [mattrubin/authenticator#301]
Hi I lost my security code and back code to the “Authenticator app” and I need the codes. I’ve been looking everywhere on the app and I just couldn’t find it.

**Comment by PatTheMav** [comment]
See @mattrubin's reply here: https://github.com/mattrubin/Authenticator/issues/295#issuecomment-426059571

**Comment by kuldipsinghd** [comment]
Hello I lost backup code even I didn’t understand how to creat backup if I lost my phone then how to restore all data and authenticator

**Comment by kuldipsinghd** [comment]
Is there any option available for backup

**Comment by kuldipsinghd** [comment]
Help me for this

**Comment by mattrubin** [comment]
I'm sorry for the long-overdue reply!

This project has been unmaintained for several years, and as I work to catch up on all of the open issues and feedback, I'm closing all issues older than a year. If, after all this time, you still have a question or are in need of help with the app, please feel free to re-open this issue.
