### ISSUE TITLE
Encrypted itunes

### ISSUE THREAD

**Issue by beks887** [mattrubin/authenticator#320]
Hello! I have a problem, I lost my phone, but I have back up on the itunes on my laptop, i restored back up on my new phone, everything was fine except the authenticator app codes didn’t back up, please help me, I was using your app for a long time, I already did back up once and everything was fine, but this time it is not backing up the codes that I have. I have a lot of codes that I need, what can I do, I still have the old back up on my laptop. Waiting for your response

**Comment by beaucollins** [comment]
When you restored your phone from backup did you use iTunes to do this?

1. Plug your phone in via USB
2. Select the device icon in the toolbar next to the media dropdown
3. Select "Summary" from the left source list
4. There should be a "Backups" section in the main window

<img width="821" alt="image" src="https://user-images.githubusercontent.com/19795/60619558-cefac000-9d8d-11e9-8a40-123316273150.png">

You should be able to click on the "Restore Backup" button to restore the phone via an encrypted backup stored on your computer.
