### ISSUE TITLE
Restored Encrypted iTunes Backup - No Codes! 

### ISSUE THREAD

**Issue by SemoTech** [mattrubin/authenticator#321]
I just restored an encrypted backup from an iPhone XS Max to an older iPhone 8 Plus and none of the 2FA tokens were restored!! The backup was encrypted and stored locally on my Mac. I still have access to the encrypted backup. Please advise how I can get the codes back. Thank you. 

Also, please advise on where/how the tokens are stored, in case I can restore them manually since I can always jailbreak the original iPhone to retrieve them from the filesystem if necessary.

**Comment by beaucollins** [comment]
>  I still have access to the encrypted backup. Please advise how I can get the codes back. Thank you.

The Authenticator app relies on the assumption that items stored in the keychain are included in an encrypted backup by Apple's software.

> Also, please advise on where/how the tokens are stored, in case I can restore them manually since I can always jailbreak the original iPhone to retrieve them from the filesystem if necessary.

They are stored in the Keychain via the OneTimePassword library:

https://github.com/mattrubin/OneTimePassword/tree/8e32517705c140360b2b09e655ccd70f63e15fdc

**Comment by SemoTech** [comment]
Thanks @beaucollins 

The issue was that somehow the restore was not clean, meaning the target device was not fully wiped.  That caused a lot of things to operate erratically, including Authenticator.

**Comment by beaucollins** [comment]
@SemoTech Were you able to recover your tokens from the backup at some point or were they lost?

**Comment by SemoTech** [comment]
@beaucollins indeed. By doing a clean restore to the iPhone 8 as a new device, everything came back from the encrypted backup!

**Comment by jrothlis** [comment]
I recently replaced my iPhone, and used the new(ish) direct iPhone to iPhone transfer method, and I can confirm that all tokens moved across to the new phone! So no encrypted backup, no backup of any kind, just initiate the transfer from the old phone to the new (you simply put the new phone next to the old one and a prompt pops up on the old phone asking if you'd like to transfer everything across). It worked remarkably well.

**Comment by SemoTech** [comment]
@jrothlis I wanted to do that but transferring 350G+ of data via WiFi is not my idea of fun :-) the cable method with an encrypted backup and iTunes seems to be the fastest.

**Comment by jrothlis** [comment]
350G?! Which iPhone have you got??

**Comment by SemoTech** [comment]
11 Pro Max with 512Gb. Was hoping they make it 1Gbps but hopefully the 2020 model has that capacity.
