### ISSUE TITLE
How do I get Authenticator to show up in the “Open in Authenticator” while scanning image from iPhone Camera

### ISSUE THREAD

**Issue by umairsuraj** [mattrubin/authenticator#327]

**Comment by beaucollins** [comment]
When I use the system camera with an OTP QR code in the viewfinder it prompts my phone to open Authenticator.

![IMG_0250](https://user-images.githubusercontent.com/19795/70360031-367fd480-1832-11ea-9830-d9063382f2b5.jpg)

Is this what you are asking about?

**Comment by umairsuraj** [comment]
@beaucollins yeah this one.

**Comment by umairsuraj** [comment]
> When I use the system camera with an OTP QR code in the viewfinder it prompts my phone to open Authenticator.
> 
> ![IMG_0250](https://user-images.githubusercontent.com/19795/70360031-367fd480-1832-11ea-9830-d9063382f2b5.jpg)
> 
> Is this what you are asking about?
@beaucollins yeah this one.

**Comment by beaucollins** [comment]
I'm not exactly sure. I don't recall doing anything specific to make this work. I had never tried it until responding to this specific issue.
