### ISSUE TITLE
Slow response?

### ISSUE THREAD

**Issue by ghost** [mattrubin/authenticator#328]
Other:
I’m looking for a new 2FA app and got my eyes on this one and Tofu Authenticator. But I’m a little concerned about the low level of engagement with posts here. One guy wrote about none of his Matt Rubin Authenticator data was migrated from one iPhone to a new through an encrypted backup, which is supposed to work - and he has not received an answer despite it being months ago. Was he PM’d or something? Just want to ensure I don’t start using this app if there is barely any engagement from the developer(s) and you’re left in the dark, like that guy.

**Comment by beaucollins** [comment]
> I’m looking for a new 2FA app and got my eyes on this one and Tofu Authenticator. But I’m a little concerned about the low level of engagement with posts here.

> Just want to ensure I don’t start using this app if there is barely any engagement from the developer(s) and you’re left in the dark, like that guy.

Your best bet is probably Tofu Authenticator then.

**Comment by jrothlis** [comment]
This is not someone's full time job. Code releases are extremely few and far between, and they don't listen to user requests (unless there is a bug). If you like it the way it is, then fantastic, but you will have zero luck in getting any new features implemented.

**Comment by ghost** [comment]
I understand, the author is doing this in his free time and everyone involved here is volunteering to help too. We’re all grateful that these open source projects exist. As a new github user I guess I was hoping someone would tell me ”there’s another repository where all the discussion is being had”. 

I guess this can be closed - I went for Tofu.

Cheers
