### ISSUE TITLE
Can’t use the app

### ISSUE THREAD

**Issue by morgan7787** [mattrubin/authenticator#333]
I got a new phone but now can’t use the app. I need to access some accounts online but don’t have any verification numbers or tokens. What do I do? I need help.

**Comment by reda5561** [comment]
I lost my phone and get anew one but I can’t access my applications because the code what can i do ?

**Comment by luiswte** [comment]
I Lost My phone and now i cant use the App please help...

**Comment by getangela** [comment]
I have the same problem. Got new phone and now I can't access the codes. Asks for a QR code token and I don't know where to get that. NEED HELP PLEASE

**Comment by mattrubin** [comment]
I'm sorry for the long-overdue reply!

This project has been unmaintained for several years, and as I work to catch up on all of the open issues and feedback, I'm closing all issues older than a year. If, after all this time, you still have a question or are in need of help with the app, please feel free to re-open this issue.
