### ISSUE TITLE
Codes broken ?

### ISSUE THREAD

**Issue by kylehill1991** [mattrubin/authenticator#334]
All of a sudden and not for the first time none of my codes work???

**Comment by beaucollins** [comment]
I'm not sure exactly where to start debugging. Some questions to start the investigation.

1. Is the time and date set correctly on your device?
2. Have you changed devices at all?
3. _None_ of the factors work for _any_ of the services or is there a particular service that fails?

**Comment by kylehill1991** [comment]
It’s just coinbase that doesn’t work?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mattrubin** [comment]
I'm sorry for the long-overdue reply!

This project has been unmaintained for several years, and as I work to catch up on all of the open issues and feedback, I'm closing all issues older than a year. If, after all this time, you still have a question or are in need of help with the app, please feel free to re-open this issue.
