### ISSUE TITLE
Not a single pin works

### ISSUE THREAD

**Issue by kassius79** [mattrubin/authenticator#335]
I've tried all 8 pins that I use not a single one works. Every single one is invalid. Yes I wait the 60 seconds for a fresh one. Tried 8/10 times. No luck. I checked my Iphone > Settings> date/time is automatic has been. The app was fine this morning. 

I am running an update for iphone. I can't reset the 2factor login for one of these unless I can login to reset it and issue myself a barcode. What a pain in the butt..

**Comment by beaucollins** [comment]
> I've tried all 8 pins that I use not a single one works.

You have eight different OTP codes for unique services and when you attempt to use any of them they fail?

**Comment by mattrubin** [comment]
I'm sorry for the long-overdue reply!

This project has been unmaintained for several years, and as I work to catch up on all of the open issues and feedback, I'm closing all issues older than a year. If, after all this time, you still have a question or are in need of help with the app, please feel free to re-open this issue.
