### ISSUE TITLE
Code generated from my Authenticator is not working 

### ISSUE THREAD

**Issue by emmachoko** [mattrubin/authenticator#338]
I can't use the code generated by the Authenticator app on my iPhone5 to login to my Facebook account for the past three weeks now, please kindly assist me thanks.

**Comment by beaucollins** [comment]
I'm sorry to hear you can't sign into Facebook @emmachoko.

If the OTP passcode for Facebook that is generated by Authenticator does not allow you to sign in, the only remedy that I know of is to use a [Recovery Code][] that Facebook gave you when you turned on two-factor authentication.

[Recovery Code]: https://www.facebook.com/help/148104135383285

Can you provide the version of iOS you are currently running on your device?

@mattrubin Do you know of any reason the Authenticator app would fail to work on an iPhone 5. The Apple website doesn't show which version of iOS is supported. I don't think it technically is supported in any way.

**Comment by emmachoko** [comment]
My phone is iPhone5,The iOS version is 10.3.4 and I was not given any recovery code by Facebook and I don't know why it would work thanks.

**Comment by mattrubin** [comment]
I'm sorry for the long-overdue reply!

This project has been unmaintained for several years, and as I work to catch up on all of the open issues and feedback, I'm closing all issues older than a year. If, after all this time, you still have a question or are in need of help with the app, please feel free to re-open this issue.
