### ISSUE TITLE
Authenticator not working

### ISSUE THREAD

**Issue by nancyluft** [mattrubin/authenticator#340]
I have a new iPhone and Authenticator does not work. I am locked out of my Coinbase and part of me unlocking it needs my 2 step veification code. Can you please help. Thanks, Nancy

**Comment by suchislife801** [comment]
In order to achieve this you must:

1.  Download and Install iTunes
2.  Connect Old iPhone via USB to iTunes
3.  Create Encrypted backup
4.  Disconnect Old iPhone
5.  Connect New iPhone via USB to iTunes
6.  Restore Encrypted backup to New iPhone
7.  Done

**Comment by mattrubin** [comment]
Your two-factor authentication tokens are only stored locally on your physical device. They can be transferred to a new phone via [Quick Start](https://support.apple.com/en-us/HT210216) or an [encrypted (iTunes or Finder) backup](https://support.apple.com/en-us/HT205220), but they are not included in iCloud backups.

Here's a few things you could try:

- If you have an [encrypted (iTunes or Finder) backup](https://support.apple.com/en-us/HT205220) of your previous phone, you could restore it to recover your two-factor tokens.
- Many apps and websites that offer two-factor authentication give a set of "recovery codes" to help you recover access to your account if you lose your phone. If you have recovery codes, you could use them to log in and disable or reset two-factor authentication on your accounts. (Some apps also support SMS-based two-factor authentication for account recovery.)
- If neither of the above works, you can try reaching out to the support for the app or website you no longer have access to and request their help recovering access to you accounts. Coinbase has [a support page related to 2-step verification](https://help.coinbase.com/en/coinbase/managing-my-account/get-back-into-my-account/2-step-verification-troubleshooting#duo-and-google-authenticator-totp); you may want to try the steps under the heading "I no longer have access to my old mobile device".

I hope that helps!
