### ISSUE TITLE
Snapchat code issue

### ISSUE THREAD

**Issue by omar-1995** [mattrubin/authenticator#342]
Hey there 
I have used the authenticator app on my snapchat account and i updated my iphone and lost the code you gave me 
Is there any solution that can get me a new code now 
I have my email and phone number that connected to the snapchat working well 

Sorry if there any language mistakes because its not my main language

**Comment by suchislife801** [comment]
No. This is not possible.

The very meaning of 2FA is to prevent exactly recovery to the highest possible extent. During the activation process, your service provider gives you a set of codes to print and keep for your records in case this happens. If you did not print it or write them down, you can go ahead and consider this catastrophic.

**Comment by mattrubin** [comment]
Your two-factor authentication tokens are only stored locally on your physical device. They can be transferred to a new phone via [Quick Start](https://support.apple.com/en-us/HT210216) or an [encrypted (iTunes or Finder) backup](https://support.apple.com/en-us/HT205220), but they are not included in iCloud backups.

Here's a few things you could try:

- If you have an [encrypted (iTunes or Finder) backup](https://support.apple.com/en-us/HT205220) of your previous phone, you could restore it to recover your two-factor tokens.
- Many apps and websites that offer two-factor authentication give a set of "recovery codes" to help you recover access to your account if you lose your phone. If you have recovery codes, you could use them to log in and disable or reset two-factor authentication on your accounts. (Some apps also support SMS-based two-factor authentication for account recovery.)
- If neither of the above works, you can try reaching out to the support for the app you no longer have access to and request their help recovering access to you accounts. Snapchat's support page for two-factor authentication is here: https://support.snapchat.com/en-US/a/enable-login-verification.

I hope that helps!
