### ISSUE TITLE
Snapchat Issue

### ISSUE THREAD

**Issue by burlbrash** [mattrubin/authenticator#343]
I used the Authenticator on my Snapchat on my phone for a 2 factor authentication and someone attempted to hack my account 2 nights ago and logged me out and I changed the password and when I went to log in and then put in the code that’s generated by the app, it says the code is wrong every single time.  Am I doing something wrong?

**Comment by suchislife801** [comment]
No. This is not possible.

The very meaning of 2FA is to prevent exactly recovery to the highest possible extent. During the activation process, your service provider gives you a set of codes to print and keep for your records in case this happens. If you did not print it or write them down, you can go ahead and consider this catastrophic.

**Comment by mattrubin** [comment]
It sounds like at some point, the two-factor authentication token associated with your account was changed, possibly when you reset your password. Your best way forward is to reach out to Snapchat for support.

Snapchat's support page for two-factor authentication is here: https://support.snapchat.com/en-US/a/enable-login-verification
Their support page for a hacked account is here: https://support.snapchat.com/en-US/article/hacked-howto

I hope that helps!
