### ISSUE TITLE
2FA removal 

### ISSUE THREAD

**Issue by baelani** [mattrubin/authenticator#346]
Not really a tech based issue. I had my phone out when I went to shower, during then my little siblings were playing with my phone. They fiddled too much and ended up deleting half of my 2FA security keys. In one of my accounts, I got logged out of it, and I didn’t screenshot or save my back-ups. I was wondering if there was a way to remove that, or I could get access to my back up codes.

**Comment by suchislife801** [comment]
No. This is not possible.

The very meaning of 2FA is to prevent exactly recovery to the highest possible extent. During the activation process, your service provider gives you a set of codes to print and keep for your records in case this happens. If you did not print it or write them down, you can go ahead and consider this catastrophic.

**Comment by mattrubin** [comment]
Your two-factor authentication tokens are only stored locally on your device, and the makers of this app never have access to your tokens or to any of your accounts on other websites or apps, so unfortunately we can't help you turn off two-factor authentication and can't provide any backup codes. Here's a few things you could try:

- If you have an [encrypted (iTunes or Finder) backup](https://support.apple.com/en-us/HT205220) of your phone from before you lost it, you could restore it to recover your two-factor tokens.
- In addition to recovery codes, some websites also support SMS-based two-factor authentication for account recovery. If you also set up two-factor authentication with your phone number, you might be able to log in and disable or reset two-factor authentication on your accounts.
- If neither of the above works, you can try reaching out to the support for the website or app you no longer have access to and request their help recovering access to your accounts.

I hope that helps!
