### ISSUE TITLE
Access to contacts without a user's permission?

### ISSUE THREAD

**Issue by lifepillar** [mattrubin/authenticator#347]
Hi,
nice app! I was a bit surprised, though, to notice that the Account Name field auto-completes addresses from Contacts, even if I was not asked to give access to that (the app only asks for access to the camera). Why is that?

**Comment by mattrubin** [comment]
The Authenticator app _never_ accesses your contacts, and doesn't have any control over autocomplete. The "Account Name" field on the manual token entry screen is marked as an email type field, so the iOS operating system may try to be helpful by autocompleting email addresses. **In particular, if you're seeing your email address suggested in a gray bar just above the keyboard, that is the iOS [predictive text](https://support.apple.com/guide/iphone/use-predictive-text-iphd4ea90231/ios) feature.** Even if the operating system offers your email address as a suggestion or autocomplete, it is only ever accessible to Authenticator if you accept the suggestion, and even then it is only ever saved locally on your phone.

**Comment by lifepillar** [comment]
Thanks for the explanation! Just to be clear, I was not suggesting that the app
is doing something shady (bypassing iOS security features would be a fact!), just curious what the mechanism was.

Please keep up with the good work!

**Comment by mattrubin** [comment]
Thanks! I wasn't feeling accused – just wanted to be extra-clear the app can be trusted not to do anything shady!
