### ISSUE TITLE
Verified Instagram Account

### ISSUE THREAD

**Issue by Inner18** [mattrubin/authenticator#348]
I have a verified instagram account where I'm suppose to use Two Factor Authentication. I changed my password on instagram and when I tried to log in again I was unable to do so because Instagram is not accepting the numbers you game me. 3 days have passed to no avail, what can I possibly to do to get this app to work like it supposed to

**Comment by mattrubin** [comment]
You may be able to regain access to your Instagram account through a linked phone number or Facebook account, but if you are still having trouble you can try to request support from Instagram following the advice at [their "I can't log in" help page](https://help.instagram.com/374546259294234).
