### ISSUE TITLE
Can’t access data on new phone 

### ISSUE THREAD

**Issue by szabo13** [mattrubin/authenticator#351]
I can not use this app on my new device nor can I figure out how to cancel ... this is a big problem since I have two factor set with many apps!!! What do I do???

**Comment by cfarregarres** [comment]
No puedo recuperar mis códigos y estoy muy preocupada por no poder acceder a cuentas

**Comment by mattrubin** [comment]
Your two-factor authentication tokens are only stored locally on your physical device. They can be transferred to a new phone via [Quick Start](https://support.apple.com/en-us/HT210216) or an [encrypted (iTunes or Finder) backup](https://support.apple.com/en-us/HT205220), but they are not included in iCloud backups.

Here's a few things you could try:

- If you have an [encrypted (iTunes or Finder) backup](https://support.apple.com/en-us/HT205220) of your previous phone, you could restore it to recover your two-factor tokens.
- Many apps and websites that offer two-factor authentication give a set of "recovery codes" to help you recover access to your account if you lose your phone. If you have recovery codes, you could use them to log in and disable or reset two-factor authentication on your accounts. (Some apps also support SMS-based two-factor authentication for account recovery.)
- If neither of the above works, you can try reaching out to the support for the app you no longer have access to and request their help recovering access to you accounts.

I hope that helps!
