### ISSUE TITLE
Removal of 2FA 

### ISSUE THREAD

**Issue by peternana11** [mattrubin/authenticator#352]
Hi, 
I have set up my account validation with the Authenticator app but now I’m unable to get token because I lost my phone. So can you please help and remove my details from the app so I can login into my account please. 
email: registered with account is [redacted].

**Comment by suchislife801** [comment]
No. This is not possible.

The very meaning of 2FA is to prevent exactly recovery to the highest possible extent. During the activation process, your service provider gives you a set of codes to print and keep for your records in case this happens. If you did not print it or write them down, you can go ahead and consider this catastrophic.

**Comment by mattrubin** [comment]
Your two-factor authentication tokens are only stored locally on your device, and the makers of this app never have access to your tokens or to any of your accounts on other websites or apps. Here's a few things you could try:

- If you have an [encrypted (iTunes or Finder) backup](https://support.apple.com/en-us/HT205220) of your phone from before you lost it, you could restore it to recover your two-factor tokens.
- Many websites that offer two-factor authentication give a set of "recovery codes" to help you recover access to your account if you lose your phone. If you have recovery codes, you could use them to log in and disable or reset two-factor authentication on your accounts. (Some websites also support SMS-based two-factor authentication for account recovery.)
- If neither of the above works, you can try reaching out to the support for the website or app you no longer have access to and request their help recovering access to your accounts.

I hope that helps!
