### ISSUE TITLE
Can I retrieve Secret Key?

### ISSUE THREAD

**Issue by vcsyc** [mattrubin/authenticator#353]
Hi!
I am using this app, but I encountered a problem.
I got locked out from the FB account completely.
I have entered the secret key from FB to the app and it generates the code, but it doesn't work.

I'm not sure if the settings should be Time Based or Counter Based (with different SHA options).
The only way for me to resolve this issue is to get the secret key and try different options though this app or try that key with another app in order to gain access to my account.

Is there a way to find and retrieve the secret key?
I've got this app installed on iPhone and Mac.
I'm not a dev, so I would highly appreciate help with this issue.

Thanks.

**Comment by suchislife801** [comment]
No. There is not. You are so in trouble if you've lost it.

**Comment by mattrubin** [comment]
Facebook two-factor authentication tokens are time-based, six digits, and use SHA-1, all of which are the defaults in Authenticator. The secret key you'd need for manual token entry is a sequence of 32 letters and numbers, though scanning the QR code Facebook offers is the easiest method of entry.
 
Here are a few Facebook help center articles that might help:

- [I can't log in to Facebook.](https://www.facebook.com/help/105487009541643)
- [What is two-factor authentication and how does it work on Facebook?](https://www.facebook.com/help/148233965247823)
- [How do I recover an old Facebook account I can't log into?](https://www.facebook.com/help/231208473756221)
