### ISSUE TITLE
I reset the iPhone and I don’t know how to get my Authenticator now

### ISSUE THREAD

**Issue by kellendir** [mattrubin/authenticator#354]
The title says everything

**Comment by wyethpro** [comment]
can we fix this problem?

**Comment by mattrubin** [comment]
Your two-factor authentication tokens are only stored locally on your device, so if your iPhone was reset, the tokens were deleted. Here's a few things you could try:

- If you have an [encrypted (iTunes or Finder) backup](https://support.apple.com/en-us/HT205220) of your phone from before you reset it, you could restore it to recover your two-factor tokens.
- Many websites that offer two-factor authentication give a set of "recovery codes" to help you recover access to your account if you lose your phone. If you have recovery codes, you could use them to log in and disable or reset two-factor authentication on your accounts. (Some websites also support SMS-based two-factor authentication for account recovery.)
- If neither of the above works, you can try reaching out to the support for the website you no longer have access to and request their help recovering access to you accounts.

I hope that helps!
