### ISSUE TITLE
where do i find a facebook token if I cant log in on any devices? 

### ISSUE THREAD

**Issue by caseyjane05** [mattrubin/authenticator#355]
where do i find a facebook token if I cant log in on any devices?

**Comment by mattrubin** [comment]
Here are a few Facebook help center articles that might help:

- [I can't log in to Facebook.](https://www.facebook.com/help/105487009541643)
- [What is two-factor authentication and how does it work on Facebook?](https://www.facebook.com/help/148233965247823)
- [How do I recover an old Facebook account I can't log into?](https://www.facebook.com/help/231208473756221)
