### ISSUE TITLE
Gain access to Instagram

### ISSUE THREAD

**Issue by ahadesquieu** [mattrubin/authenticator#362]
Hello. I have deleted the authenticator app and downloaded again. Now, I can not access to my Instagram account. Unfortunately, I do not have recovery codes. What can I do now?

**Comment by mattrubin** [comment]
I'm sorry to hear you can't access your Instagram account! Your two-factor authentication tokens are only stored locally on your device, so they were deleted when you deleted the Authenticator app. Here's a few things you could try:

- If you have an [encrypted (iTunes or Finder) backup](https://support.apple.com/en-us/HT205220) of your phone from before you deleted Authenticator, you could restore it to recover your two-factor tokens.
- If you linked your Instagram account to your Facebook account, or to your phone number, you might be able to regain access that way.
- If neither of the above works, you can try to request support from Instagram following the advice at [their "I can't log in" help page](https://help.instagram.com/374546259294234).

I hope that helps!
