### ISSUE TITLE
transferring everything to a new iphone

### ISSUE THREAD

**Issue by extraitt** [mattrubin/authenticator#363]
today I got a new Iphone and I can't seem to transfer my current codes, if theres a way to do it I would love help, I couldn't find anything online about it.

**Comment by suchislife801** [comment]
In order to achieve this you must:

1. Download and Install iTunes
2. Connect Old iPhone via USB to iTunes
3. Create Encrypted backup
4. Disconnect Old iPhone
5. Connect New iPhone via USB to iTunes
6. Restore Encrypted backup to New iPhone
7. Done

**Comment by mattrubin** [comment]
Your two-factor authentication tokens are only stored locally on your physical device, and are not included in iCloud backups, so it takes a few extra steps to transfer them to a new iPhone. The easiest method is to use iOS [Quick Start](https://support.apple.com/en-us/HT210216) when setting up a new phone. You can also create an [encrypted backup](https://support.apple.com/en-us/HT205220) of your old phone using iTunes – or, on recent versions of macOS, Finder – and restore it to your new phone.
