### ISSUE TITLE
Difficult to delete tokens on small screens

### ISSUE THREAD

**Issue by McMalloc** [mattrubin/authenticator#364]
The button with the red icon to delete a token from the list is very small. I needed so many tries to hit it that I thought deleting is broken. I assume this is an usability issue for other users with small screens, too. I'm on an iPhone SE (4 inches display).

Thank you for your work!

**Comment by mattrubin** [comment]
Thanks for the feedback! I've seen plenty of previous feedback that deleting tokens was _too easy_, which led to [disabling swipe-to-delete](https://github.com/mattrubin/Authenticator/pull/251) and [adding a confirmation message before deleting](https://github.com/mattrubin/Authenticator/pull/217), but this is the first I've heard that deleting tokens is now too hard.

The red delete icon is the standard one offered by default on iOS. I'll try playing with the app on a smaller screen size and see if I have any ideas, but given the amount of work involved in customizing the delete button and the risk of making accidental deletion too easy, this is unlikely to get changed any time soon.

**Comment by McMalloc** [comment]
Thanks Matt, I completely understand. I'd prefer tapping a few more times to accidentally deleting a token, too. Given the lack of similiar feedback you gathered so far this seems to be a general problem beetween my fingers and this specific screen size.
