### ISSUE TITLE
please help for getting new codes on my new phone

### ISSUE THREAD

**Issue by ufukbcr** [mattrubin/authenticator#365]
hello dear, i need really help, couldnt handle the issue. i currently change my phone, both of two are iphone. i use your app for entering stock markets like ftx,gateio . And i have MONEY on that. problem is ; i dont know about that i cant transport all my knowledge to my new iphone on this authenticator app when reload with i cloud. after noticing that i find my old phone and reload my icloud. But at this time when i enter the app again, i cant get a new codes from that platform, beside there are no platform added before on that app. as now i cant enter my any account that using with your this app, please help quickly, 
ufukbcr@gmail.com
+905447451422 
contact me so important

**Comment by ufukbcr** [comment]
by the way i have tried today to load backups from old phone via apple finder( it dont use itunes any more to create backups) but before trying  i deleted all arrangement on my old phone, because i didnt know i cant transport tokens via icloud backups, what do ypu suggest?

**Comment by mattrubin** [comment]
I'm sorry for the long-overdue reply!

This project has been unmaintained for several years, and as I work to catch up on all of the open issues and feedback, I'm closing all issues older than a year. If, after all this time, you still have a question or are in need of help with the app, please feel free to re-open this issue.
