### ISSUE TITLE
HOW TO Disable Authenticator Codes HELPPPP

### ISSUE THREAD

**Issue by Sleepynuts** [mattrubin/authenticator#368]
Hi, I want to disable 2 of my Authenticator codes for my Snapchat, Dropbox. 

How do I go about that? I went into both apps but don’t see a disable 2FA disable button. Can anyone help this is killing me

**Comment by yb66** [comment]
@Sleepynuts 

To [disable Dropbox 2FA](https://help.dropbox.com/teams-admins/team-member/enable-two-step-verification) go to step 5 "Toggle Two-step verification to On. " and toggle it off.

To disable Snapchat 2FA just [follow the steps in this video](https://www.youtube.com/watch?v=kbVZslHitIE) and toggle off the one for an authenticator app.

Regards,
iain
