### ISSUE TITLE
Got Phone Replaced and Lost Codes - HELP

### ISSUE THREAD

**Issue by sincerelyjane** [mattrubin/authenticator#371]
I took my iPhone in to be repaired and they lost all of my data. I had not backed up my phone, so I received a new one. Now, I am unable to receive codes sent to the authenticator app. How am I able to resolve this issue?

**Comment by yb66** [comment]
@sincerelyjane  Do you have the backup codes (that sites give when you sign up) written down or saved somewhere else?
