### ISSUE TITLE
Got new iPhone and can’t login on IG

### ISSUE THREAD

**Issue by mary2021s** [mattrubin/authenticator#372]
I didn’t have an encrypted backpack now can’t login on IG with my new iPhone. The app doesn’t generate codes

**Comment by Lisandra9822** [comment]
Same Problem here.

**Comment by id21-space-developer** [comment]
Solution is I had an encrypted backup on mac with active keychain or you have lost all keys, also apple is clear when you need to make a new update you must first have the security of your data make a backup, greetings

**Comment by mattrubin** [comment]
If you have lost or erased your old phone and can't recover your tokens from an encrypted backup, you can either use a backup code (https://help.instagram.com/1006568999411025) or try contacting Instagram support to recover your account (https://www.instagram.com/hacked/).
