### ISSUE TITLE
Can’t get verification code

### ISSUE THREAD

**Issue by Thedeputy53** [mattrubin/authenticator#373]
Good morning
I enabled 2FA verification last night and I scanned the QR code twice and it gave me two different options for codes for my account. I deleted one of the codes and the code that I deleted obviously would be the code I need to get into my account. I am presently locked out of my account and I called my bank and they can’t reset sue to needing the code as well. 
Is it possible to get a new QR scan bar or a new code to access my account. My account was for […]. My number is […] and email is […]. You can reach me at anytime. 
Your consideration in this matter would greatly be appreciated.

**Comment by mattrubin** [comment]
I'm sorry for the long-overdue reply!

This project has been unmaintained for several years, and as I work to catch up on all of the open issues and feedback, I'm closing all issues older than a year. If, after all this time, you still have a question or are in need of help with the app, please feel free to re-open this issue.
