### ISSUE TITLE
Authenticator app 

### ISSUE THREAD

**Issue by ghost** [mattrubin/authenticator#377]
I had the Authenticator app on my old iPhone and now I have it on my new iPhone. But I didn’t save the backup codes for some of the websites is their any way I can get the Authenticator app codes back?

**Comment by dleicht** [comment]
Without an encrypted backup and without access to your old phone your tokens are pretty much gone...

**Comment by jtatarchuk** [comment]
What if we did do an encrypted backup? How do we transfer to a new phone?

**Comment by dleicht** [comment]
> What if we did do an encrypted backup? How do we transfer to a new phone?

You'd simply restore the new phone from the encrypted backup, for example using iTunes (or whatever software you used to get that encrypted backup in the first place).

When your new phone is restored, the authenticator app AND all your tokens will be back.

You might be wondering: the old and the new phone are different devices and your backup might not be compatible with your new phone. Don't worry, it's just about the data. Encrypted backup and restore is the only way to transfer your tokens onto a new device. Imagine you could simply copy security tokens between any devices, it would totally defeat the purpose.

Just give it a try 😊

**Comment by mattrubin** [comment]
You can find instructions on how to restore an encrypted backup to you new phone here: https://support.apple.com/en-us/HT204184#computer
You can find additional tips on confirming your backups are encrypted here: https://support.apple.com/en-us/HT205220#check
