### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by Spd68** [mattrubin/authenticator#378]
I have recently received a new phone and I am unable to gain access to my Authenticator app on my old phone as it is broken. Is there any other way I can verify my identity as I have been locked out of all social media and other things thanks

**Comment by dleicht** [comment]
Assuming you did back up earlier (an encrypted itunes backup is mandatory here - tokens are not stored in an unencrypted backup) you could restore the new phone from that backup and thus get your tokens back.

Maybe it's not too late to back up your old phone. Does it turn on?

**Comment by ghost** [comment]
The app is locally stored. You will need to have a encrypted backup of your iPhone to get anything back. 
If you do not have your phone still or unable to connect it up to your computer, then you will need to revert to recovery codes or contacting the support channels for social media. 
Make a habit of backing up your iPhone!
