### ISSUE TITLE
Como desativar o código de autenticação 

### ISSUE THREAD

**Issue by Caiofg92** [mattrubin/authenticator#381]
Como desativar o código de autenticação em um site .consigo fazer o login coloco a senha e quando pede o código o App gera um código inválido e agora estou impossibilitado de entrar no site pois não tenho a chave secret.

**Comment by mattrubin** [comment]
I'm sorry for the long-overdue reply!

This project has been unmaintained for several years, and as I work to catch up on all of the open issues and feedback, I'm closing all issues older than a year. If, after all this time, you still have a question or are in need of help with the app, please feel free to re-open this issue.
