### ISSUE TITLE
Facebook login Issue

### ISSUE THREAD

**Issue by DigitalTiwari** [mattrubin/authenticator#384]
I am not able to use my FB app from past 5-6 months.  I have upgraded my iphone and reset the previous one because of which I lost the access of third party authenticator app.

**Comment by mattrubin** [comment]
If you have an [encrypted (iTunes or Finder) backup](https://support.apple.com/en-us/HT205220) of your phone from before you reset your old phone, you could restore it to recover your two-factor tokens.

If you don't have a recoverable encrypted backup of your old phone, you'll need to work with Facebook to recover access to your account. Here are a few Facebook help center articles that might help:
- [I turned on two-factor authentication on Facebook but now I can't log in.](https://www.facebook.com/help/147926301947841)
- [I can't log in to Facebook.](https://www.facebook.com/help/105487009541643)
- [How do I recover an old Facebook account I can't log into?](https://www.facebook.com/help/231208473756221)
