### ISSUE TITLE
Getting back access 

### ISSUE THREAD

**Issue by Getitback2022** [mattrubin/authenticator#388]
Hey so I am desperate for help. I got a new phone and my authenticator info did not transfer. is there any way that your support team can help me restore my coinbase link in the app. I have been locked out of coinbase for a month with all my funds locked taking multiple multiple losses due to market volatility . All i need is access to my authenticator to access my coinbase account. I have contacted coinbase, reset my account, verified my account and for a month I have not been able to get any help from anywhere. Please help.

**Comment by id21-space-developer** [comment]
Solution is I had an encrypted backup on mac with active keychain or you have lost all keys

**Comment by mattrubin** [comment]
Authenticator tokens are stored only on your local device, so unfortunately there's nothing we can do to restore them.


If you have lost or erased your old phone and can't recover your tokens from an encrypted backup, you will have to use Coinbase's account recovery process: https://help.coinbase.com/en/contact-us/support-faq/coinbase/2-step-verification-account-recovery
