### ISSUE TITLE
Please help ( Authenticator app back up ) 

### ISSUE THREAD

**Issue by Adm0111** [mattrubin/authenticator#393]
Dear Authenticator app team,

wish this e-mail finds you well. Please note that i had your authenticator app installed on my other iPhone. Unfortunately, that iPhone got broken :( and I can’t turn it on no more. It’s damaged. The important point that all my codes are there inside the Authenticator app and I can’t get access to them. Now I have my IPhone11 and I installed the Authenticator app but I can’t get an access to the codes I had on the other phone. So please help me with a way to get a back up for the codes in my iPhone the I’m currently using.

Thank you

**Comment by joeo2010** [comment]
Was this resolved?

**Comment by id21-space-developer** [comment]
> Gentile team dell'app Authenticator,
> 
> vorrei che questa e-mail ti trovasse bene. Tieni presente che ho installato la tua app di autenticazione sull'altro mio iPhone. Sfortunatamente, quell'iPhone si è rotto :( e non posso più accenderlo. È danneggiato. Il punto importante che tutti i miei codici sono lì all'interno dell'app Authenticator e non posso accedervi. Ora ho il mio IPhone11 e ho installato l'app Authenticator ma non riesco ad accedere ai codici che avevo sull'altro telefono. Quindi per favore aiutami con un modo per ottenere un backup per i codici nel mio iPhone che sto attualmente utilizzando.
> 
> Grazie
Solution is I had an encrypted backup on mac with active keychain or you have lost all keys

**Comment by id21-space-developer** [comment]
> Gentile team dell'app Authenticator,
> 
> vorrei che questa e-mail ti trovasse bene. Tieni presente che ho installato la tua app di autenticazione sull'altro mio iPhone. Sfortunatamente, quell'iPhone si è rotto :( e non posso più accenderlo. È danneggiato. Il punto importante che tutti i miei codici sono lì all'interno dell'app Authenticator e non posso accedervi. Ora ho il mio IPhone11 e ho installato l'app Authenticator ma non riesco ad accedere ai codici che avevo sull'altro telefono. Quindi per favore aiutami con un modo per ottenere un backup per i codici nel mio iPhone che sto attualmente utilizzando.
> 
> Grazie
Solution is I had an encrypted backup on mac with active keychain or you have lost all keys

**Comment by id21-space-developer** [comment]
Solution is I had an encrypted backup on mac with active keychain or you have lost all keys

**Comment by mattrubin** [comment]
Your two-factor authentication tokens are only stored locally on your device, so they are not automatically synced or transferred to a new phone. Here's a few things you could try:

- If you have an [encrypted (iTunes or Finder) backup](https://support.apple.com/en-us/HT205220) of your phone from before you reset it, you could restore it to recover your two-factor tokens.
- Many websites that offer two-factor authentication give a set of "recovery codes" to help you recover access to your account if you lose your phone. If you have recovery codes, you could use them to log in and disable or reset two-factor authentication on your accounts. (Some websites also support SMS-based two-factor authentication for account recovery.)
- If neither of the above works, you can try reaching out to the support for the website you no longer have access to and request their help recovering access to you accounts.
