### ISSUE TITLE
I lost all my account because of trusted the information here

### ISSUE THREAD

**Issue by zaindxbtv** [mattrubin/authenticator#395]
I make restore to my iphone and i have 1 iCloud backup and 3 i magazine backup and 1 iTunes 
And I can't restore authenticator app im from 5 days trying i lost access to instagram twitter snapchat because I don't saved backup codes

**Comment by id21-space-developer** [comment]
You should have made sure that the keys were active on mac before backing up in + you should have made sure that from the first backup onwards they were all encrypted.

**Comment by mattrubin** [comment]
Your two-factor authentication tokens are only stored locally on your device, and are not backed up to iCloud or to an unencrypted iTunes backup. Here's a few things you could try:

- If you have an [_encrypted_ (iTunes or Finder) backup](https://support.apple.com/en-us/HT205220) of your phone from before you reset it, you could restore it to recover your two-factor tokens.
- Many websites that offer two-factor authentication give a set of "recovery codes" to help you recover access to your account if you lose your phone. If you have recovery codes, you could use them to log in and disable or reset two-factor authentication on your accounts. (Some websites also support SMS-based two-factor authentication for account recovery.)
- If neither of the above works, you can try reaching out to the support for the website you no longer have access to and request their help recovering access to you accounts.

**Comment by spygency1** [comment]
NEED URGENT HELP?!!

NOTE:MESSAGE ONLY THIS ACCOUNT
#🇬🇧Expert Here To Assist In Any Cyber Issues General_Hacking_Recovery_Spy_Blackmail_Stolen,Lost BTC_Hacked Phones ☎️ 📥
🌎Facebook hacking - recovery
🌎Instagram hacking - recovery
🌎Snapchat hacking - recovery
🌎Lost money(investment scams) recovery
🌎Cheating partner spy (online)
🌎Crypto wallet hacking
🌎Phone hacks📱
🌎Message hacks & tweaks

For swift response send a message to my social media accounts, we are active 24/7 to solve all your Online ETHICAL HACKING issues 

INSTAGRAM 📥 spygency.1
EMAIL 📧 spygency@gmail.com
