### ISSUE TITLE
Authenticator token disappeared for Facebook 

### ISSUE THREAD

**Issue by Masglobal-markus** [mattrubin/authenticator#396]
Hello I used to have a token for Facebook 2FA. Now it is gone for some reason but my others are still there. Anyway I can recover it? Facebook says this is the only way to get in.

**Comment by Masglobal-markus** [comment]
I do not have backup recovery codes saved.

**Comment by id21-space-developer** [comment]
Solution is I had an encrypted backup on mac with active keychain or you have lost all keys,You should have made sure that the keys were active on mac before backing up in + you should have made sure that from the first backup onwards they were all encrypted.

**Comment by mattrubin** [comment]
I'm sorry to hear this! Were there any changes to your device (a software update, a restore to a new phone) around the time you lost your Facebook token? Is there any chance you or someone else accidentally deleted it?

If you don't have an encrypted backup from before your token was lost, and you don't have backup recovery codes, you can try going through Facebook's account recovery process here: https://www.facebook.com/help/105487009541643
