### ISSUE TITLE
Migrate to new iphonr

### ISSUE THREAD

**Issue by rhondalynnk** [mattrubin/authenticator#397]
Do you have instructions about how to move the app from one iPhone to another please?

**Comment by AngusP** [comment]
(I'm a user not a contributor)

The app says if (and only of) you back up your iPhone to iTunes or Finder using Encrypted backups, then the codes will be included in the backup. For security reasons codes are not included in iCloud backups.

So unfortunately if you don't use that specific required backup method to move to a new phone, you will have to manually migrate all your codes, which usually means setting up 2FA again on each service you use it for.

**Comment by HugoTron** [comment]
@AngusP Can you tell me how I transfer my Auth factor from my old iPhone to the new one step by step? 

What do I need to do?

**Comment by mattrubin** [comment]
Your two-factor authentication tokens are only stored locally on your physical device, and are _not_ included in iCloud backups, so it takes a few extra steps to transfer them to a new iPhone.

The easiest method is to use iOS [Quick Start](https://support.apple.com/en-us/HT210216) when setting up a new phone, making sure to choose the option to transfer data _directly from your previous device_ (_not_ downloading an iCloud backup). Another method is to create an [_encrypted_ backup](https://support.apple.com/en-us/HT205220) of your old phone in Finder – or, on older versions of macOS, iTunes – and restore it to your new phone.

With either method, you should open the Authenticator app on your new phone to **confirm the transfer was successful _before_ erasing your old phone**.
