### ISSUE TITLE
Lost 2 factor link 

### ISSUE THREAD

**Issue by Mikenero84** [mattrubin/authenticator#402]
Hi mate, hope you can help I have changed phones and has this app of yours as a 2 factor rolling code. I can fond my initial setup. Please help me to try get it fixed? Thanks Michail

**Comment by mattrubin** [comment]
Your two-factor authentication tokens are only stored locally on your device, so they are not automatically synced or transferred to a new phone. Here's a few things you could try:

- If you have an [encrypted (iTunes or Finder) backup](https://support.apple.com/en-us/HT205220) of your phone from before you reset it, you could restore it to recover your two-factor tokens.
- Many websites that offer two-factor authentication give a set of "recovery codes" to help you recover access to your account if you lose your phone. If you have recovery codes, you could use them to log in and disable or reset two-factor authentication on your accounts. (Some websites also support SMS-based two-factor authentication for account recovery.)
- If neither of the above works, you can try reaching out to the support for the website you no longer have access to and request their help recovering access to you accounts.
