### ISSUE TITLE
All Authenticator number fails

### ISSUE THREAD

**Issue by Jfrgtx** [mattrubin/authenticator#403]
I have 9 accounts Associated with the app; each one , when I enter the code that Authenticator is giving me ; each of them are failing and rejected !! 
how can I solve the issue ?

**Comment by jiripospisil** [comment]
Is your phone's time correct?

**Comment by Jfrgtx** [comment]
Correct compare to what?

**Comment by Jfrgtx** [comment]
That’s true, I pass time on automatic and it works thanks for the info
