### ISSUE TITLE
No updates in 3 years

### ISSUE THREAD

**Issue by shabadibi** [mattrubin/authenticator#404]
Hi guys,
the latest version off the iOS app is 3 years old and, for this reason, i was considering to migrate to other apps.
Infact, I was wondering if this was an abandoned project and if the app is still safe to use for such a sensitive matter.

Thanks to anyone who will share its thought about it
Shabadibi

**Comment by beaucollins** [comment]
I have no way of updating the app, unfortunately. I have switched to using Apple's built-in macOS and iOS second factor support in Keychain.app

https://www.macobserver.com/tips/deep-dive/ios-15-add-2fa/

**Comment by mattrubin** [comment]
> I was wondering if this was an abandoned project

_Abandoned_? Not quite. _Chronically unmaintained_? Unfortunately, yes.

 > if the app is still safe to use for such a sensitive matter

I still personally use the app, and it has remained stable over the last few years. Apple's keychain, which the Authenticator app uses internally, remains a secure storage repository for your tokens.

That said, I understand your concern about an aging app. While my available time is quite limited, I've recently started work on a small maintenance update to test and re-build the app with the latest iOS SDK. If you are interested in testing the updated version before its public release, you can join the beta here: https://testflight.apple.com/join/J8Zrq5bJ

**Comment by shabadibi** [comment]
That's great! I just started to test it.
I really appreciate your work
