### ISSUE TITLE
Switching from device to another with same Authenticator using iCloud ( iPhone Device )

### ISSUE THREAD

**Issue by HugoTron** [mattrubin/authenticator#406]
Greetings. I have a question. 
Will my authentication codes remain the same with apple iCloud when I transfer data from my old phone to my new iPhone? 

In other words, will my authenticator codes remain on my new phone, or will disappear?
Because someone wrote here about the issues that it´s a problem for him and he lost his job I am wondering. 

If so this app is useless and high risk for anyone.

**Comment by mattrubin** [comment]
Your two-factor authentication tokens are only stored locally on your physical device, and are _not_ included in iCloud backups, so it takes a few extra steps to transfer them to a new iPhone.

The easiest method is to use iOS [Quick Start](https://support.apple.com/en-us/HT210216) when setting up a new phone, making sure to choose the option to transfer data _directly from your previous device_ (_not_ downloading an iCloud backup). Another method is to create an [_encrypted_ backup](https://support.apple.com/en-us/HT205220) of your old phone in Finder – or, on older versions of macOS, iTunes – and restore it to your new phone.

With either method, you should open the Authenticator app on your new phone to **confirm the transfer was successful _before_ erasing your old phone**.
