### ISSUE TITLE
Generated codes no longer valid in IOS 17.3.1

### ISSUE THREAD

**Issue by Razique** [mattrubin/authenticator#432]
Hi,
I have noticed something really unexpected. After updating my phone to iOS 17.3.1, all the generated codes no longer work.
I thought I wrongly types the code or that they expired, but I have tried multiple times against multiple services. 
I have been using the app for years without any issue, and this is the first time this happens.
Could it be that the update broke the way the codes are generated?

**Comment by Razique** [comment]
Yup, I confirm that something is broken :(
I was able to deactivate 2FA for one of my websites, and during the setup phase, after scanning the QR code, the application is unable to generate valid codes.

I have installed Ravio and generated a new code for one of my websites, and this is working as expected.

**Comment by jiripospisil** [comment]
Just tested this with two different websites and everything is working fine for me. Is your clock on the device correct?

**Comment by Razique** [comment]
Oh shoot, you're right, the time was one-minute off on my phone after restart :/ 🤦🏼 
Everything is working now, sorry for the noise
