### ISSUE TITLE
App is blank. 

### ISSUE THREAD

**Issue by brabauer** [mattrubin/authenticator#437]
App open up blank with no options after updating to iOS 18 beta. Understood the risks of using a beta software but wanted to report it your way as I use your app for all my codes. 

iOS 18 beta iPhone 15 pro max

**Comment by 2twToddWilson** [comment]
> App open up blank with no options after updating to iOS 18 beta. Understood the risks of using a beta software but wanted to report it your way as I use your app for all my codes.
> 
> iOS 18 beta iPhone 15 pro max

I have the exact same issue. Same phone, same behavior.

**Comment by Suhayl** [comment]
Same here. On iOS 18 beta 1 on an iPhone 13 Pro Max.

**Comment by Markgarland1971** [comment]
> App open up blank with no options after updating to iOS 18 beta. Understood the risks of using a beta software but wanted to report it your way as I use your app for all my codes.
> 
> iOS 18 beta iPhone 15 pro max

I have the exact same issue.

**Comment by matticolo17** [comment]
> App open up blank with no options after updating to iOS 18 beta. Understood the risks of using a beta software but wanted to report it your way as I use your app for all my codes.
> 
> iOS 18 beta iPhone 15 pro max

Same issue, how can we solve it?

**Comment by brabauer** [comment]
Seems to be functional again once I updated to 18 beta 2. Will have to see how the app continues to function throughout the beta program.

**Comment by mattrubin** [comment]
As of beta 6 (22A5338b), Authenticator still appears to be working fine on iOS 18. I'll continue to monitor this as we approach the final release candidate.

Please feel free to re-open an issue if you encounter any more issues on the iOS 18 beta.

**Comment by mattrubin** [comment]
Tested with no issues on iOS 18 beta 8 (22A5350a)
