### ISSUE TITLE
iPhone 6

### ISSUE THREAD

**Issue by sandykoe** [mattrubin/Authenticator#8]
The interface needs to be updated a little to support the new high-resolution screens on the iPhone 6 and 6 plus.

**Comment by mattrubin** [comment]
The bars and bar buttons are the standard size provided by UIKit. In retrospect, I suspect the issue here was that the app's UI looked small compared to other apps which hadn't been updated for the new screen sizes, and would be displayed as scaled-up versions of the iPhone 5 screen size.

**Comment by beaucollins** [comment]
I'm on an iPhone 6 Plus and don't notice anything out of the ordinary concerning UI element sizes.
