### ISSUE TITLE
Authenticator Not Working

### ISSUE THREAD

**Issue by jendavis1** [mattrubin/Authenticator#82]
Hello, 
I tried to get an authentication code today. I tapped on my app on my iPhone as usual and instead of a code appearing, the message "No Tokens" "Tap + to add a new token" appears. How do I fix this so that I can get to my email account?
Kind regards,
Jennifer

**Comment by mattrubin** [comment]
Hi Jennifer,

That message appears when the app finds no tokens saved in the system keychain. Did you get a new phone, or reset your current phone? For security reasons, the tokens are stored only on the phone they are first entered into, and are not synced in any way to other devices. If you install the app on a new phone or restore an unencrypted backup after resetting your current phone, the secret keys will not be preserved.

When you enabled two-factor authentication for your email account, you should have been given a "recovery code" to use in case your phone or its authentication token were lost. With the recovery code, you should be able to access your email account and set up two-factor authentication again with a new token.

**Comment by London5000** [comment]
I'm having the same problem as Jennifer.  Old phone broke and my authenticator won't pull up codes on new iphone.  I have no idea what my recovery code is.  My life's money are tied up in my crypto and I can't get to it to buy or sell.  Can you help me?

**Comment by London5000** [comment]
I will try anything and happy to pay someone in advance a fee for there help.  I don't know where else to turn.

**Comment by mattrubin** [comment]
As mentioned above, two-factor tokens are only stored in the physical iPhone into which they are entered, and are only included in encrypted backups made with iTunes.

At the same time you set up two-factor authentication, you should have been given a "recovery token" to use in case you lost access to your two-factor device.

So your two avenues forward are:
 - restoring your phone from an encrypted iTunes backup to recover the lost tokens.
 - using recovery tokens to regain access to any accounts you are locked out of.

Some websites and services will have other ways of helping you verify your identity and regain access to your account, but that depends on the specific business prescribed of each website, and you'll need to reach out to their customer service for help.

**Comment by London5000** [comment]
Thank you Matt!

**Comment by mattrubin** [comment]
You're welcome! I hope this info is helpful, and that you regain access to your accounts!
